[config]
default_to_workspace = false

[env]
CPUS = 2
MEMORY = "512M"
QEMU = "D:/ProgramFiles/qemu/qemu-system-riscv64"
QEMU_OPTS = """
-machine virt \
-kernel target/riscv64imac-unknown-none-elf/debug/basic_os \
-smp ${CPUS} \
-m ${MEMORY} \
-nographic \
"""
QEMU_GDB_OPTS = "-S -gdb tcp::26000" # The port 26000 must be the same as in the .gdbinit

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.qemu]
linux_alias = "linux_qemu"
windows_alias = "windows_qemu"

[tasks.linux_qemu]
script = "${QEMU} ${QEMU_OPTS}"
dependencies = ["build"]

[tasks.windows_qemu]
script = "%QEMU% %QEMU_OPTS%"
dependencies = ["build"]

[tasks.qemu-gdb]
linux_alias = "linux_qemu_gdb"
windows_alias = "windows_qemu_gdb"

[tasks.linux_qemu_gdb]
script = "${QEMU} ${QEMU_OPTS} ${QEMU_GDB_OPTS}"
dependencies = ["build"]

[tasks.windows_qemu_gdb]
script = "%QEMU% %QEMU_OPTS% %QEMU_GDB_OPTS%"
dependencies = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]
