[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsrc/arch/riscv/linker.ld"]
runner = "cargo make qemu-riscv"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/arch/x86/linker.ld"]
runner = "cargo make qemu-x86"

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/arch/arm/linker.ld"]
runner = "cargo make qemu-arm"
